Repository wso2/apk, pull requests merged in 2022-11, with the labels that each got.

#141 Remove product-microgateway dependencies from apk
  adapter/go.mod
  adapter/go.sum
  adapter/internal/adapter/adapter.go
  adapter/internal/api/apis_impl.go
  adapter/internal/discovery/xds/server.go
  adapter/internal/grpc-client/grpcExecutor.go
  adapter/internal/notifier/deployment_notifier.go
  adapter/internal/oasparser/config_generator.go
  adapter/internal/oasparser/envoyconf/access_loggers.go
  adapter/internal/oasparser/envoyconf/compression_filter.go
  adapter/internal/oasparser/envoyconf/http_filters.go
  adapter/internal/oasparser/envoyconf/listener.go
  adapter/internal/oasparser/envoyconf/response_mapper.go
  adapter/internal/oasparser/envoyconf/routes_configs.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
  adapter/internal/oasparser/model/api_operation.go
  adapter/internal/oasparser/model/mgw_swagger.go
  adapter/internal/oasparser/model/open_api.go
  adapter/internal/svcdiscovery/watcher.go
  adapter/pkg/auth/auth.go
  adapter/pkg/auth/auth_test.go
  adapter/pkg/health/api/wso2/health/service/health.pb.go
  adapter/pkg/health/api/wso2/health/service/health_grpc.pb.go
  adapter/pkg/health/controlplane.go
  adapter/pkg/health/health.go
  adapter/pkg/loggers/logger.go
  adapter/pkg/soaputils/soap.go
  adapter/pkg/tlsutils/tls_utils.go
  management-server/go.mod
  management-server/go.sum
Labels: Type/Task

#189 Remove APKCtl folder
  ctl/build.gradle
  ctl/gradle.properties
  ctl/gradle/wrapper/gradle-wrapper.properties
  ctl/gradlew
  ctl/gradlew.bat
Labels: Type/Task, Priority/Low

#198 Update readme with implementation details and other additional inform…
  README.md
Labels: documentation, Type/Docs, Priority/Normal

#205 adding API delete call support
  runtime/runtime-domain-service/ballerina/Dependencies.toml
  runtime/runtime-domain-service/ballerina/K8sClient.bal
  runtime/runtime-domain-service/ballerina/api_service.bal
Labels: Type/Improvement, Priority/Normal
