Repository wso2/apk, pull requests merged in 2024-02, with the labels that each got.

#1987 Increase pod readiness time in git integration tests
  .github/workflows/integration-test.yml
Labels: trigger-action

#1990 Increase wait time for deployments in go-integration tests
  .github/workflows/integration-test.yml
Labels: trigger-action

#2009 fixing subscription issue
  common-controller/internal/utils/event_utils.go
  gateway/enforcer/org.wso2.apk.enforcer/src/main/java/org/wso2/apk/enforcer/subscription/SubscriptionDataStoreImpl.java
Labels: trigger-action

#2014 Adding changes/fixes related graphql APIs
  common-go-libs/config/crd/bases/dp.wso2.com_gqlroutes.yaml
  helm-charts/crds/dp.wso2.com_gqlroutes.yaml
  runtime/config-deployer-service/ballerina/APIClient.bal
  runtime/config-deployer-service/ballerina/Dependencies.toml
  runtime/config-deployer-service/ballerina/Dependencies.toml.template
  runtime/config-deployer-service/ballerina/modules/model/GraphQLRoute.bal
  test/cucumber-tests/src/test/resources/tests/api/GraphQL.feature
Labels: apim-agent, trigger-action

#1997 Semantic Versioning based Intelligent Routing
  .github/workflows/integration-test.yml
  adapter/config/default_config.go
  adapter/config/types.go
  adapter/internal/discovery/xds/semantic_versioning.go
  adapter/internal/discovery/xds/server.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters.go
  adapter/internal/oasparser/envoyconf/routes_with_clusters_test.go
  adapter/pkg/loggers/logger.go
  adapter/pkg/semanticversion/semantic_version.go
  helm-charts/README.md
  helm-charts/templates/data-plane/gateway-components/log-conf.yaml
  helm-charts/values.yaml.template
Labels: trigger-action

#2029 Enable Semantic versioning for Cucumber tests
  .github/workflows/integration-test.yml
Labels: trigger-action

#2024 Add integration and unit tests for the Semantic versioning feature
  adapter/internal/discovery/xds/semantic_versioning_test.go
  adapter/pkg/semanticversion/semantic_version.go
  adapter/pkg/semanticversion/semantic_version_test.go
  test/cucumber-tests/CRs/artifacts.yaml
  test/cucumber-tests/src/test/resources/artifacts/apk-confs/semantic-versioning/sem_api_v1-0.yaml
  test/cucumber-tests/src/test/resources/artifacts/apk-confs/semantic-versioning/sem_api_v1-1.yaml
  test/cucumber-tests/src/test/resources/artifacts/apk-confs/semantic-versioning/sem_api_v1-5.yaml
  test/cucumber-tests/src/test/resources/artifacts/apk-confs/semantic-versioning/sem_api_v2-1.yaml
  test/cucumber-tests/src/test/resources/tests/api/SemanticVersioning.feature
Labels: trigger-action

#2038 Fix TLS for Redis configuration in load balancer
  helm-charts/templates/data-plane/ratelimiter/ratelimiter-deployment.yaml
Labels: review/done, trigger-action

#2046 Fixing licence headers
  .github/workflows/agent-integration-test.yml
  test/apim-apk-agent-test/cucumber-tests/src/test/java/org/wso2/apk/integration/api/SharedContext.java
Labels: trigger-action
